# Generated by Django 3.2.4 on 2021-06-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('match_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('week', models.IntegerField()),
                ('season', models.IntegerField()),
                ('ot', models.IntegerField()),
                ('teama_name', models.CharField(max_length=50)),
                ('teama_pts', models.IntegerField()),
                ('teama_pts_q1', models.IntegerField()),
                ('teama_pts_q2', models.IntegerField()),
                ('teama_pts_q3', models.IntegerField()),
                ('teama_pts_q4', models.IntegerField()),
                ('teama_yds', models.IntegerField()),
                ('teama_yds_rush', models.IntegerField()),
                ('teama_yds_pass', models.IntegerField()),
                ('teama_tds', models.IntegerField()),
                ('teama_tds_rush', models.IntegerField()),
                ('teama_tds_pass', models.IntegerField()),
                ('teama_tos', models.IntegerField()),
                ('teama_4d_att', models.IntegerField()),
                ('teama_4d_comp', models.IntegerField()),
                ('teama_sacks', models.IntegerField()),
                ('teama_sack_yds', models.IntegerField()),
                ('teama_rtn_td', models.IntegerField()),
                ('teama_drives', models.IntegerField()),
                ('teamh_name', models.CharField(max_length=50)),
                ('teamh_pts', models.IntegerField()),
                ('teamh_pts_q1', models.IntegerField()),
                ('teamh_pts_q2', models.IntegerField()),
                ('teamh_pts_q3', models.IntegerField()),
                ('teamh_pts_q4', models.IntegerField()),
                ('teamh_yds', models.IntegerField()),
                ('teamh_yds_rush', models.IntegerField()),
                ('teamh_yds_pass', models.IntegerField()),
                ('teamh_tds', models.IntegerField()),
                ('teamh_tds_rush', models.IntegerField()),
                ('teamh_tds_pass', models.IntegerField()),
                ('teamh_tos', models.IntegerField()),
                ('teamh_4d_att', models.IntegerField()),
                ('teamh_4d_comp', models.IntegerField()),
                ('teamh_sacks', models.IntegerField()),
                ('teamh_sack_yds', models.IntegerField()),
                ('teamh_rtn_td', models.IntegerField()),
                ('teamh_drives', models.IntegerField()),
            ],
            options={
                'db_table': 'raw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SummaryView',
            fields=[
                ('match_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('week', models.IntegerField()),
                ('season', models.IntegerField()),
                ('teama_name', models.CharField(max_length=50)),
                ('teamh_name', models.CharField(max_length=50)),
                ('pts', models.IntegerField()),
                ('ptsqf', models.IntegerField()),
                ('yds', models.IntegerField()),
                ('tds', models.IntegerField()),
                ('tos', models.IntegerField()),
                ('fdpc', models.IntegerField()),
                ('sacks', models.IntegerField()),
                ('sackyds', models.IntegerField()),
                ('rtns', models.IntegerField()),
                ('drives', models.IntegerField()),
                ('drvtdpc', models.IntegerField()),
                ('close', models.IntegerField()),
                ('closeqf', models.IntegerField()),
                ('ot', models.IntegerField()),
            ],
            options={
                'db_table': 'summary_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebView',
            fields=[
                ('match_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('week', models.IntegerField()),
                ('season', models.IntegerField()),
                ('teama_name', models.CharField(max_length=50)),
                ('teamh_name', models.CharField(max_length=50)),
                ('fun_score', models.FloatField()),
            ],
            options={
                'db_table': 'web_view',
                'managed': False,
            },
        ),
    ]
